### ISSUE TITLE
dmstr/yii2-pages-module deps

### ISSUE THREAD

**Issue by Quexer69** [dmstr/yii2-backend-module#1]
@schmunk42 Why do we need this deps ?

https://github.com/dmstr/yii2-backend-module/blob/master/composer.json#L15

I think handle this in our `dmstr/yii2-cms-metapackage` should be enough!

**Comment by schmunk42** [comment]
Because of https://github.com/dmstr/yii2-backend-module/blob/fd5b1a2526d507d54f7021e290db542ad7a06ea8/src/views/layouts/main.php#L46-L52

In the future the backend module should be able to build several dashboards with Twig templates.

**Comment by Quexer69** [comment]
You mean the `prototype module` or `pages module`?

We use the cms metapackage, which requires the `pages module` already!

https://github.com/dmstr/yii2-cms-metapackage/blob/master/composer.json#L9

I think the `backend` module should be more *standalone*. Prototyping can be included, but a pages module should be optional.

EDIT:

That part has to be rendered via twig...

https://github.com/dmstr/yii2-backend-module/blob/fd5b1a2526d507d54f7021e290db542ad7a06ea8/src/views/layouts/_sidebar.php#L38-47

... so that everyone can use a custom implementation of the sidebar menu, if wanted.

**Comment by schmunk42** [comment]
> You mean the prototype module or pages module?

Both. Pages is required for building the menu, Prototype for the contents.

A *standalone*  version would be nice, but has no priority currently.
