### ISSUE TITLE
Change default heart icon

### ISSUE THREAD

**Issue by StalkAlex** [dmstr/yii2-backend-module#3]
Is there any way to change it by default? Heart symbol is not appropriate for state services, now I need to change layout of every module that is opened in backend view.

**Comment by schmunk42** [comment]
We could use a settings key, like `backend.adminlte.navbarIcon` WDYT? - see also https://github.com/dmstr/yii2-backend-module#settings

PRs always welcome.

**Comment by StalkAlex** [comment]
Ok, I'll make in a few days.

**Comment by StalkAlex** [comment]
Should I use master version or you could make a new release including this feature?

**Comment by schmunk42** [comment]
Available in https://github.com/dmstr/yii2-backend-module/releases/tag/0.6.0
